apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-certificate>
  tls.key: <base64-encoded-key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: my-image:latest
        ports:
        - containerPort: 443
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/ssl/certs
        - name: tls-keys
          mountPath: /etc/ssl/private
        env:
        - name: TLS_CERT_FILE
          value: /etc/ssl/certs/tls.crt
        - name: TLS_KEY_FILE
          value: /etc/ssl/private/tls.key
      volumes:
      - name: tls-certs
        secret:
          secretName: my-secret
          items:
          - key: tls.crt
            path: tls.crt
      - name: tls-keys
        secret:
          secretName: my-secret
          items:
          - key: tls.key
            path: tls.key
